### ISSUE TITLE
Feature > Additional secrets to vault seed

### ISSUE THREAD

**Issue by kuwas** [npm-wharf/fabrik8#6]
Current these arguments and corresponding values are not in the vault seed.

* `--arg-readableBuckets` for tick
* `--arg-supporthub_vault_address` for support hub
* `--arg-supporthub_vault_role_id` for support hub
* `--arg-supporthub_vault_secret_id` for support hub
* `--arg-supporthub_vault_secret_prefix` for support hub

**Comment by aearly** [comment]
Fixed, in another repo.
